################################################################
# traefik 기본인증 미들웨어
################################################################
http:
  middlewares:
    basic-auth:
      basicAuth:
        usersFile: "/etc/traefik/users/userfile"
