################################################################
# Synology Drive
# custom url: https://drive.nas.hyeon.pro/
################################################################

http:
  routers:
    syno_drive:
      entryPoints:
        - websecure
      service: syno_drive
      rule: Host(`drive.nas.hyeon.pro`)
      tls:
        certResolver: leresolver

  services:
    syno_drive:
      loadBalancer:
        servers:
          - url: http://192.168.1.159:65433
        passHostHeader: true
