################################################################
# Synology file station
# custom url: https://file.nas.hyeon.pro/
################################################################

http:
  routers:
    syno_file:
      entryPoints:
        - websecure
      service: syno_file
      rule: Host(`file.nas.hyeon.pro`)
      tls:
        certResolver: leresolver

  services:
    syno_file:
      loadBalancer:
        servers:
          - url: http://192.168.1.159:65432
        passHostHeader: true
